# Generated by Django 3.2 on 2020-12-06 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201205_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickUpTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 17, 18, 54, 411344)),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_id',
            field=models.IntegerField(default=68738),
        ),
    ]
