# Generated by Django 3.1.3 on 2020-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201116_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='inv_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
