# Generated by Django 3.1.2 on 2020-11-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201124_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='inv_count',
            field=models.IntegerField(default=0),
        ),
    ]
