# Generated by Django 3.1.3 on 2020-11-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isFilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isMade',
            field=models.BooleanField(default=False),
        ),
    ]
