# Generated by Django 3.1.2 on 2020-12-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201127_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_id',
            field=models.IntegerField(default=14537),
        ),
    ]
