# Generated by Django 3.0.4 on 2020-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_fooditem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_id',
            field=models.IntegerField(default=124871),
        ),
    ]
